name: build
on: [ push, pull_request ]
jobs:
  java-build:
    name: Build java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: corretto
      - name: Build
        run: chmod +x ./gradlew && ./gradlew mongodb-search-core:build mongodb-search-gradle-plugin:build
      - uses: actions/upload-artifact@v3
        with:
          name: java packages
          path: |
            mongodb-search-core/build/libs
            mongodb-search-interface/build/libs
            mongodb-search-gradle-plugin/build/libs
  node-build:
    name: Build node
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mongodb-search-interface/node
    needs: java-build
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        run: yarn && yarn build
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: java-build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: java packages
      - uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: corretto
      - name: Build
        run: chmod +x ./gradlew && ./gradlew mongodb-search-core:test
