name: build
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: corretto
      - name: Grant permission and publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: chmod +x ./gradlew && ./gradlew publish --no-daemon
      - name: Setup tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
      - name: Publish to Gradle Plugin Portal
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'plugin')
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew mongodb-search-gradle-plugin:publishPlugins
      - name: Setup Node
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Version
        if: startsWith(github.ref, 'refs/tags/v')
        run: cd mongodb-search-interface/node && node .ci/set-version ${{ steps.tag.outputs.tag }}
      - name: Build package
        if: startsWith(github.ref, 'refs/tags/v')
        run: cd mongodb-search-interface/node && yarn && yarn build
      - name: Deploy package
        if: startsWith(github.ref, 'refs/tags/v')
        run: cd mongodb-search-interface/node && yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
