name: publish libraries
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
    branches:
      - '**'
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: TEST
        run: echo "workflow build=${{github.event.workflow_run.conclusion}}"
  deploy-core:
    name: Publish core
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: java artifacts
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
      - name: Publish libraries
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish --no-daemon
  deploy-interface:
    name: Publish interface
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mongodb-search-interface/node
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: java artifacts
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - id: tag
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
      - run: node .ci/set-version ${{ steps.tag.outputs.tag }}
      - name: Publish package
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
