name: publish
on:
  push:
    tags:
      - 'v\d+'
  pull_request:
    tags:
      - 'v\d+'
jobs:
  deploy-core:
    name: Publish core
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Packages
      - uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: corretto
      - name: Publish libraries
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: chmod +x ./gradlew && ./gradlew publish --no-daemon
  deploy-plugin:
    name: Publish plugin
    runs-on: ubuntu-latest
    needs: test
    paths:
      - '**/mongodb-search-gradle-plugin/**'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: Packages
    - uses: actions/setup-java@v3.3.0
      with:
        java-version: 11
        distribution: corretto
    - id: tag
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
    - name: Publish plugin
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      run: chmod +x ./gradlew && ./gradlew mongodb-search-gradle-plugin:publishPlugins
  deploy-interface:
    name: Publish interface
    runs-on: ubuntu-latest
    working-directory: ./mongodb-search-interface/node
    needs: test
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: node .ci/set-version ${{ steps.tag.outputs.tag }}
      - name: Publish package
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
