name: publish plugin
run-name: Release ${{ github.ref_name }} plugin
on:
  workflow_run:
    workflows: [build]
    types:
      - completed
jobs:
  call-build:
    uses: ./.github/workflows/build.yml
  deploy-plugin:
    name: Publish plugin
    runs-on: ubuntu-latest
    needs: call-build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: java artifacts
    - uses: actions/setup-java@v3.3.0
      with:
        java-version: 11
        distribution: corretto
    - uses: tj-actions/changed-files@v40
      with:
        files: mongodb-search-gradle-plugin/**
    - name: Publish plugin
      if: steps.changed-files-yaml.outputs.any_changed == 'true'
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      run: chmod +x ./gradlew && ./gradlew mongodb-search-gradle-plugin:publishPlugins
