name: publish libraries
on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*
jobs:
  deploy-core:
    name: Publish core
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: java artifacts
      - uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: corretto
      - name: Publish libraries
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: chmod +x ./gradlew && ./gradlew publish --no-daemon
  deploy-interface:
    name: Publish interface
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mongodb-search-interface/node
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: java artifacts
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: node .ci/set-version ${{ steps.tag.outputs.tag }}
      - name: Publish package
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
