name: publish plugin
on:
  workflow_run:
    workflows: build
    types: [ completed ]
  push:
    tags:
      - v*
    paths:
      - '**/mongodb-search-gradle-plugin/**'
  pull_request:
    tags:
      - v*
    paths:
      - '**/mongodb-search-gradle-plugin/**'
jobs:
  deploy-plugin:
    name: Publish plugin
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: java artifacts
    - uses: actions/setup-java@v3.3.0
      with:
        java-version: 11
        distribution: corretto
    - id: tag
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
    - name: Publish plugin
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      run: chmod +x ./gradlew && ./gradlew mongodb-search-gradle-plugin:publishPlugins
